module.exports = {
    LOAD_HOMES: "LOAD_HOMES",
    LOAD_HOMES_SUCCESS: "LOAD_HOMES_SUCCESS",
    LOAD_HOMES_ERROR: "LOAD_HOMES_ERROR",
    UPDATE_FILTER: "UPDATE_FILTER",
    REMOVE_FILTER: "REMOVE_FILTER"
};