module.exports = {
    LOAD_HOMES: "LOAD_HOMES",
    LOAD_HOMES_SUCCESS: "LOAD_HOMES_SUCCESS",
    LOAD_HOMES_ERROR: "LOAD_HOMES_ERROR",
    UPDATE_FILTER: "UPDATE_FILTER",
    REMOVE_FILTER: "REMOVE_FILTER",
    ADD_TO_SHORTLIST:"ADD_TO_SHORTLIST",
    REMOVE_FROM_SHORTLIST:"REMOVE_FROM_SHORTLIST",
    POST_SHORTLIST_TO_SERVER:"POST_SHORTLIST_TO_SERVER",
    POST_SHORTLIST_TO_SERVER_SUCCESS:"POST_SHORTLIST_TO_SERVER_SUCCESS",
    UPDATE_CARESEEKER_EMAIL:"UPDATE_CARESEEKER_EMAIL",
    UPDATE_CARESEEKER_EMAIL_SUCCESS:"UPDATE_CARESEEKER_EMAIL_SUCCESS"
};